name: release-mac

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  release-mac:
    name: release-mac
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install pnpm
        run: npm install -g pnpm@^10

      - name: Install dependencies
        run: pnpm install

      - name: Packing for mac
        run: |
          rm -rf ./.github
          npm run pack:mac
          npm run pack:mac-arm

      - name: Create zip package
        run: |
          npm run build:mac-zip
          npm run build:mac-arm-zip

      - name: Upload binaries to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: './dist/installers/*.*'
          tag: ${{ github.ref }}
          file_glob: true

